[project]
name = "tubes3-hrdbawel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyqt6>=6.9.0",
    "pymupdf>=1.26.1",
    "faker>=37.4.0",
    "pymysql>=1.1.1",
]
